CREATE TABLE `isystem`.`T_CUSTOMER_TYPES` (
  `F_CUSTOMER_TYPE_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_CUSTOMER_TYPE_CAPTION` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`F_CUSTOMER_TYPE_ID`)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `isystem`.`T_CUSTOMERS` (
  `F_CUSTOMER_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_TITLE` VARCHAR(10) NOT NULL,
  `F_FIRST_NAME` VARCHAR(50) NOT NULL,
  `F_FIRST_NAME_METAPHONE` VARCHAR(12) NOT NULL,
  `F_LAST_NAME` VARCHAR(50) NOT NULL,
  `F_LAST_NAME_METAPHONE` VARCHAR(12) NOT NULL,
  `F_MODIFIED_WHEN` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `F_TYPE` BIGINT(12) NOT NULL,
  PRIMARY KEY (`F_CUSTOMER_ID`),
  UNIQUE INDEX `F_CUSTOMER_ID_UNIQUE` (`F_CUSTOMER_ID` ASC)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
