INSERT INTO `isystem`.`T_CUSTOMER_TYPES` (`F_CUSTOMER_TYPE_CAPTION`) VALUES ('Residential');
INSERT INTO `isystem`.`T_CUSTOMER_TYPES` (`F_CUSTOMER_TYPE_CAPTION`) VALUES ('Small/Medium Business');
INSERT INTO `isystem`.`T_CUSTOMER_TYPES` (`F_CUSTOMER_TYPE_CAPTION`) VALUES ('Enterprise');

INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Fred', 'FRT', 'Clark', 'KLRK', '2015-08-01 01:20:05', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Anderson', 'ANTRSN', 'Lee', 'L', '2015-08-01 01:20:24', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Helena', 'HLN', 'Gonzalez', 'KNSLS', '2015-08-01 01:20:42', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Stiven', 'STFN', 'King', 'KNK', '2015-08-01 01:20:58', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mrs', 'Monica', 'MNK', 'Nelson', 'NLSN', '2015-08-01 01:21:16', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'William', 'WLM', 'Phillips', 'FLPS', '2015-08-01 01:21:35', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Martin', 'MRTN', 'Wilson', 'WLSN', '2015-08-01 01:21:55', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Veronica', 'FRNK', 'Stub', 'STB', '2015-08-01 01:22:09', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Mark', 'MRK', 'Scott', 'SKT', '2015-08-01 01:25:00', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Lola', 'LL', 'CocaCola', 'KKKL', '2015-08-01 01:25:16', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Demmi', 'TM', 'Moore', 'MR', '2015-08-01 01:25:32', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Jone', 'JN', 'Jones', 'JNS', '2015-08-01 01:25:48', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Anderson', 'ANTRSN', 'Silva', 'SLF', '2015-08-01 10:13:28', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Petty', 'PT', 'Green', 'KRN', '2015-08-01 10:13:49', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Harry', 'HR', 'Potter', 'PTR', '2015-08-01 10:14:00', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mrs', 'Hermiona', 'HRMN', 'Granger', 'KRNJR', '2015-08-01 10:14:15', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Will', 'WL', 'Smith', 'SM0', '2015-08-01 10:14:30', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Valery', 'FLR', 'Ross', 'RS', '2015-08-01 10:14:54', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Salema', 'SLM', 'Haieck', 'HK', '2015-08-01 10:45:11', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Karlos', 'KRLS', 'Provaadoz', 'PRFTS', '2015-08-03 17:27:32', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Adolf', 'ATLF', 'Trump', 'TRMP', '2015-08-03 18:00:08', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Fred', 'FRT', 'Huston', 'HSTN', '2015-08-05 23:56:07', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'George', 'JRJ', 'Washington', 'WXNKTN', '2015-08-06 00:00:04', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mrs', 'Emma', 'EM', 'Wattson', 'WTSN', '2015-08-06 12:11:47', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Piter', 'PTR', 'PrestonMarket', 'PRSTNMRKT', '2015-08-06 20:17:54', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mrs', 'Serena', 'SRN', 'Williams', 'WLMS', '2015-08-06 22:41:26', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Frederik', 'FRTRK', 'Begbeder', 'BKBTR', '2015-08-07 11:53:07', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Samuel', 'SML', 'Jakson', 'JKSN', '2015-08-07 17:59:35', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Stefany', 'STFN', 'Mayer', 'MYR', '2015-08-07 15:41:05', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Andrew', 'ANTR', 'Rayel', 'RYL', '2015-08-07 16:51:27', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'William', 'WLM', 'Nelson', 'NLSN', '2015-08-07 18:00:11', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Valery', 'FLR', 'Devil', 'TFL', '2015-08-08 20:51:05', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mrs', 'Laura', 'LR', 'Barns', 'BRNS', '2015-08-08 21:55:52', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Michael', 'MXL', 'Klaus', 'KLS', '2015-08-08 22:30:41', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Ms', 'Katerin', 'KTRN', 'Kristof', 'KRSTF', '2015-08-08 22:32:50', '2');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Kevin', 'KFN', 'Levron', 'LFRN', '2015-08-08 22:40:55', '3');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Dr', 'Arnold', 'ARNLT', 'Shwarcenegger', 'XWRSNKR', '2015-08-08 22:41:44', '1');
INSERT INTO `isystem`.`T_CUSTOMERS` (`F_TITLE`, `F_FIRST_NAME`, `F_FIRST_NAME_METAPHONE`, `F_LAST_NAME`, `F_LAST_NAME_METAPHONE`, `F_MODIFIED_WHEN`, `F_TYPE`)
VALUES ('Mr', 'Mitchel', 'MXL', 'Flayvor', 'FLFR', '2015-08-08 22:53:20', '2');